import { RepositoriesRequest } from 'classes/request/RepositoriesRequest'
import { BaseLayout } from 'components/layout/BaseLayout'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <BaseLayout>
      <Head>
        <title>Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    </BaseLayout>
  )
}

export default Home


export async function getServerSideProps() {

  const requestRepositories = new RepositoriesRequest();

  const data = {repositories: []};

  try {
    const randomRepositories = await requestRepositories.getRepositoriesByNameTechnologyRandom();
    //if(randomRepositories?.items) data.repositories = randomRepositories?.items;
  } catch (error) {
    
  }

  return {
    props: {

    }, // will be passed to the page component as props
  }
}
